# Generated by Django 4.0.4 on 2022-06-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumb',
            field=models.ImageField(blank=True, default='product.jpg', null=True, upload_to=''),
        ),
    ]
